# Base de datos Supabase (PostgreSQL)

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xxejhmmzehadkfrzlsdw
spring.datasource.password=databaseStoq1783
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Puerto del servidor (Render inyecta PORT)
server.port=${PORT:8080}

# CORS: lista separada por comas para permitir frontends concretos
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://69c76b9becee2700087d65df--stoqsa.netlify.app}

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
